baseURL: "https://bwicht.github.io"
disablePathToLower: trues
enableGitInfo: true
languages: 
  en: 
    contentDir: content
    languageName: English
    weight: 1
markup: 
  goldmark: 
    renderer: 
      unsafe: true
  tableOfContents: 
    startLevel: 1
menu: 
  after: 
    - 
      name: Github
      url: "https://github.com/alex-shpak/hugo-book"
      weight: 10
    - 
      name: "Hugo Themes"
      url: "https://themes.gohugo.io/hugo-book/"
      weight: 20
    - 
      name: contenu
      url: "https://bwicht.github.io/contenu/"
      weight: 20
params: 
  BookComments: true
  BookDateFormat: "January 2, 2006"
  BookEditPath: edit/master/exampleSite/content
  BookPortableLinks: true
  BookRepo: "https://github.com/alex-shpak/hugo-book"
  BookSearch: true
  BookSection: docs
  BookServiceWorker: true
  BookToC: true